# Generated by Django 5.1.3 on 2025-05-20 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingID', models.CharField(max_length=10, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar1', models.ImageField(default='listing1.jpg', upload_to='')),
                ('avatar2', models.ImageField(default='listing2.jpg', upload_to='')),
                ('avatar3', models.ImageField(default='listing3.jpg', upload_to='')),
                ('avatar4', models.ImageField(default='listing4.jpg', upload_to='')),
                ('avatar5', models.ImageField(default='listing5.jpg', upload_to='')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
