# Generated by Django 5.1.3 on 2025-05-26 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('house', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingID', models.CharField(max_length=10, null=True, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('area_sqft', models.PositiveIntegerField(help_text='Total area in square feet', null=True)),
                ('year_built', models.PositiveIntegerField(null=True)),
                ('floor_number', models.PositiveIntegerField(null=True)),
                ('total_floors', models.PositiveIntegerField(null=True)),
                ('rent', models.PositiveIntegerField(default=0)),
                ('deposit', models.PositiveIntegerField(default=0)),
                ('avatar1', models.ImageField(default='listing1.jpg', upload_to='')),
                ('avatar2', models.ImageField(default='listing2.jpg', upload_to='')),
                ('avatar3', models.ImageField(default='listing3.jpg', upload_to='')),
                ('avatar4', models.ImageField(default='listing4.jpg', upload_to='')),
                ('avatar5', models.ImageField(default='listing5.jpg', upload_to='')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('floor_plan', models.FileField(blank=True, help_text='Upload the floor plan as a PDF or image.', null=True, upload_to='')),
                ('tour', models.URLField(blank=True, help_text='Link to the 3D tour of the property.', null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='dash.address')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.listingcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
