# Generated by Django 5.1.3 on 2025-05-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_listing_title_alter_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
