# Generated by Django 5.1.3 on 2025-05-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_listing_description_listing_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
